package dev.mikko.log4jcheck;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

class ScannerTest {

    /** 造一个带 META-INF/maven/.../pom.properties 的模块 jar。 */
    private static byte[] moduleJar(String group, String module, String version,
                                    String manifestSym) throws IOException {
        ByteArrayOutputStream bos = new ByteArrayOutputStream();
        try (ZipOutputStream z = new ZipOutputStream(bos)) {
            if (manifestSym != null) {
                z.putNextEntry(new ZipEntry("META-INF/MANIFEST.MF"));
                z.write(("Manifest-Version: 1.0\r\nBundle-SymbolicName: " + manifestSym
                        + "\r\nImplementation-Version: " + version + "\r\n\r\n")
                        .getBytes(StandardCharsets.UTF_8));
                z.closeEntry();
            }
            if (group != null) {
                z.putNextEntry(new ZipEntry(
                        "META-INF/maven/" + group + "/" + module + "/pom.properties"));
                // 🔴 键序刻意打乱:必须按 key 解析,不能按行序(第 9 注实测同一批 jar 键序不同)
                z.write(("#Generated by Maven\nartifactId=" + module + "\nversion=" + version
                        + "\ngroupId=" + group + "\n").getBytes(StandardCharsets.UTF_8));
                z.closeEntry();
            }
            z.putNextEntry(new ZipEntry("org/apache/logging/log4j/Dummy.class"));
            z.write(new byte[]{(byte) 0xCA, (byte) 0xFE, (byte) 0xBA, (byte) 0xBE});
            z.closeEntry();
        }
        return bos.toByteArray();
    }

    private static Map<String, String> versions(Scanner s) {
        Map<String, String> m = new LinkedHashMap<>();
        s.artifacts().forEach(a -> m.put(a.module(), a.version().toString()));
        return m;
    }

    @Test
    @DisplayName("从 pom.properties 读出模块与版本(键序打乱也要对)")
    void readsPomProperties(@TempDir Path dir) throws IOException {
        Path jar = dir.resolve("log4j-core-2.24.0.jar");
        Files.write(jar, moduleJar("org.apache.logging.log4j", "log4j-core", "2.24.0", null));
        Scanner s = new Scanner();
        s.scan(jar);
        assertEquals(Map.of("log4j-core", "2.24.0"), versions(s));
        assertEquals("pom.properties", s.artifacts().get(0).source());
    }

    @Test
    @DisplayName("⭐ 四个模块版本不一致时要分别报出来 —— 这是本注判定粒度的前提")
    void reportsPerModuleVersions(@TempDir Path dir) throws IOException {
        Files.write(dir.resolve("log4j-core-2.25.4.jar"),
                moduleJar("org.apache.logging.log4j", "log4j-core", "2.25.4", null));
        Files.write(dir.resolve("log4j-api-2.24.0.jar"),
                moduleJar("org.apache.logging.log4j", "log4j-api", "2.24.0", null));
        Files.write(dir.resolve("log4j-1.2-api-2.20.0.jar"),
                moduleJar("org.apache.logging.log4j", "log4j-1.2-api", "2.20.0", null));
        Scanner s = new Scanner();
        s.scan(dir);
        // 🔴 「我把 log4j 升到 2.25.4 了」在这个场景里只对了三分之一。
        assertEquals("2.25.4", versions(s).get("log4j-core"));
        assertEquals("2.24.0", versions(s).get("log4j-api"));
        assertEquals("2.20.0", versions(s).get("log4j-1.2-api"));
    }

    @Test
    @DisplayName("Spring Boot fat jar 里的 BOOT-INF/lib 要穿透")
    void penetratesFatJar(@TempDir Path dir) throws IOException {
        Path app = dir.resolve("app.jar");
        try (ZipOutputStream z = new ZipOutputStream(Files.newOutputStream(app))) {
            z.putNextEntry(new ZipEntry("BOOT-INF/lib/log4j-core-2.24.0.jar"));
            z.write(moduleJar("org.apache.logging.log4j", "log4j-core", "2.24.0", null));
            z.closeEntry();
            z.putNextEntry(new ZipEntry("BOOT-INF/lib/log4j-api-2.24.0.jar"));
            z.write(moduleJar("org.apache.logging.log4j", "log4j-api", "2.24.0", null));
            z.closeEntry();
        }
        Scanner s = new Scanner();
        s.scan(app);
        assertEquals(2, s.artifacts().size());
        s.artifacts().forEach(a -> assertTrue(a.path().contains("!/"),
                "证据路径要标明它在哪个归档里:" + a.path()));
    }

    @Test
    @DisplayName("被 shade 进业务 jar 的 log4j 也要认出来(读 pom 看不见这层)")
    void findsShadedLog4j(@TempDir Path dir) throws IOException {
        Path app = dir.resolve("service-1.0.jar");
        try (ZipOutputStream z = new ZipOutputStream(Files.newOutputStream(app))) {
            z.putNextEntry(new ZipEntry(
                    "META-INF/maven/org.apache.logging.log4j/log4j-core/pom.properties"));
            z.write(("groupId=org.apache.logging.log4j\nartifactId=log4j-core\nversion=2.20.0\n")
                    .getBytes(StandardCharsets.UTF_8));
            z.closeEntry();
            z.putNextEntry(new ZipEntry("com/acme/App.class"));
            z.write(new byte[]{1});
            z.closeEntry();
        }
        Scanner s = new Scanner();
        s.scan(app);
        assertEquals(Map.of("log4j-core", "2.20.0"), versions(s));
    }

    @Test
    @DisplayName("没有 pom.properties 时退回 MANIFEST;改了文件名也要对")
    void fallsBackToManifest(@TempDir Path dir) throws IOException {
        Path jar = dir.resolve("renamed-by-devops.jar");
        Files.write(jar, moduleJar(null, "log4j-core", "2.19.0",
                "org.apache.logging.log4j.log4j-core"));
        Scanner s = new Scanner();
        s.scan(jar);
        assertEquals(Map.of("log4j-core", "2.19.0"), versions(s));
        assertEquals("MANIFEST", s.artifacts().get(0).source());
    }

    @Test
    @DisplayName("最后退回文件名,但只认这四个模块的命名")
    void fallsBackToFileName(@TempDir Path dir) throws IOException {
        ByteArrayOutputStream bos = new ByteArrayOutputStream();
        try (ZipOutputStream z = new ZipOutputStream(bos)) {
            z.putNextEntry(new ZipEntry("x/Y.class"));
            z.write(new byte[]{1});
            z.closeEntry();
        }
        Files.write(dir.resolve("log4j-layout-template-json-2.22.1.jar"), bos.toByteArray());
        Files.write(dir.resolve("some-other-lib-1.0.jar"), bos.toByteArray());
        Scanner s = new Scanner();
        s.scan(dir);
        assertEquals(Map.of("log4j-layout-template-json", "2.22.1"), versions(s));
    }

    @Test
    @DisplayName("🔴 log4j 1.x 要认出来并告警 —— 不说的话用户会以为我们也查过它")
    void warnsAboutLog4j1x(@TempDir Path dir) throws IOException {
        Path jar = dir.resolve("log4j-1.2.17.jar");
        Files.write(jar, moduleJar("log4j", "log4j", "1.2.17", null));
        Scanner s = new Scanner();
        s.scan(jar);
        assertTrue(s.artifacts().isEmpty(), "1.x 不进判定");
        assertTrue(s.warnings().stream().anyMatch(w -> w.contains("log4j 1.x")),
                "但必须明说本工具不覆盖它:" + s.warnings());
    }

    @Test
    @DisplayName("版本号解析不了要告警,不许静默丢掉")
    void warnsOnUnparsableVersion(@TempDir Path dir) throws IOException {
        Path jar = dir.resolve("log4j-core-weird.jar");
        Files.write(jar, moduleJar("org.apache.logging.log4j", "log4j-core",
                "${log4j.version}", null));
        Scanner s = new Scanner();
        s.scan(jar);
        assertTrue(s.artifacts().isEmpty());
        assertTrue(s.warnings().stream().anyMatch(w -> w.contains("这不等于「没有漏洞」")),
                "🔴 读不出版本 ≠ 没有漏洞:" + s.warnings());
    }

    @Test
    @DisplayName("🔴 回归:不是有效 zip 的 jar 解出 0 个条目**且不抛异常** —— 必须告警")
    void warnsOnBrokenArchive(@TempDir Path dir) throws IOException {
        // 建造时实测出来的静默故障:ZipInputStream 遇到非 zip 内容时
        // getNextEntry() 直接返回 null,**不抛任何异常**。
        // 于是「这个 jar 坏了」会表现成「这个 jar 里没有 log4j」——
        // 和「你很安全」长得一模一样(`10-教训.md`「静默故障最贵」同型)。
        Path jar = dir.resolve("truncated.jar");
        Files.write(jar, "PK\u0003\u0004 this is not a real zip".getBytes(StandardCharsets.UTF_8));
        Scanner s = new Scanner();
        s.scan(jar);
        assertTrue(s.artifacts().isEmpty());
        assertTrue(s.warnings().stream().anyMatch(w -> w.contains("一个条目都解不出来")
                        || w.contains("归档解析失败")),
                "🔴 必须报出来:" + s.warnings());
        assertTrue(s.warnings().stream().anyMatch(w -> w.contains("这不等于")),
                "措辞必须挡住「没扫到 = 安全」这个读法:" + s.warnings());
    }

    @Test
    @DisplayName("正常 jar 不该触发那条空归档告警(否则它会变成人人无视的噪音)")
    void noEmptyArchiveWarningForGoodJar(@TempDir Path dir) throws IOException {
        Path jar = dir.resolve("log4j-core-2.24.0.jar");
        Files.write(jar, moduleJar("org.apache.logging.log4j", "log4j-core", "2.24.0", null));
        Scanner s = new Scanner();
        s.scan(jar);
        assertFalse(s.warnings().stream().anyMatch(w -> w.contains("一个条目都解不出来")),
                "双向自测:告警不能对正常 jar 也响:" + s.warnings());
    }

    @Test
    @DisplayName("同一路径同一模块只记一条,别让人以为有两个问题")
    void deduplicates(@TempDir Path dir) throws IOException {
        Path jar = dir.resolve("log4j-core-2.24.0.jar");
        Files.write(jar, moduleJar("org.apache.logging.log4j", "log4j-core", "2.24.0",
                "org.apache.logging.log4j.log4j-core"));
        Scanner s = new Scanner();
        s.scan(jar);
        assertEquals(1, s.artifacts().size(), "pom.properties 与 MANIFEST 都在时不该记两条");
    }

    @Test
    @DisplayName("不存在的路径要告警而不是安静通过")
    void warnsOnMissingPath() throws IOException {
        Scanner s = new Scanner();
        s.scan(Path.of("Z:/definitely/not/here"));
        assertFalse(s.warnings().isEmpty());
    }
}
